hash-format = "sha256"

[[files]]
file = "config/nomorepopups.json"
hash = "3394279972b0116c3fab32a9477888da78621e0351a6dd5c2fae1ceb31cbc821"

[[files]]
file = "config/quark-common.toml"
hash = "7c8a23e8d43f8f98c5bdb0ae00da34177c47cd282d21f97ec1d74ed93108692e"

[[files]]
file = "config/rrls.toml"
hash = "718738ffebafacec5ba69a06721ffa41e1d0b47d1b39a6905c3b21639a12cdf5"

[[files]]
file = "modlist.md"
hash = "14ed040241e88deecab2b0d6c632c4fe6e3f1b3c67a170ad58a31d30eafa8b42"

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "f131905d113ba9dd127abf3c9f897aaf4ecf59657c415752533893d44cb584df"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "40bab1828ae2b4d755db64f1c887a2fe06171fad6ab54d4a1863ca5c30ff9b55"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "a966c425617e0583ccadc2fe7f521a53833c93f4aacd9c89c24ad7cc76eca97a"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "4a5c45429e2ecfac02675b036bbc6ecae2efed0edd0fd6e12adee8c56cd1a80f"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b295f82ef9223dddee5e7027cba00bc93c14a41a8479d6b9bb72fd0bba5f275e"
metafile = true

[[files]]
file = "mods/bens-sharks.pw.toml"
hash = "014b7369256a429bdcb6727dbf5eebda5b3bfcfa5135b7e3303af4d28bb4a130"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "e5df83a3dd1686106741d1d61da5869aed0537c2931a40234e1b3bd2d09e1971"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "ba1bdad41e3c9ec131330f048fc6f9bcb753ca3e9bfa1e41d60d6ca11afbc2e6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "96204145e12506e0625d8b9bfa05aad54e9a62fd511bae39f0d57fcb5e39f4cc"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "e9cfb7374590ca30ace54658e4196c6b2f3883b89fdaa4c2cfb124da37021a55"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "1e56f528d8e21b0cf9c52c3d6deea2a4eafa408170b39a070195dbf66617f373"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6a62d8663df5fe33f18c8a0d3784a3aab183b252c620c45fc98e677a71b06cde"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "317801320ec36fc5818b68cb25ab193719a144d5e29f10a85f3fbbd74aa36aeb"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "8f2270a50a633db681826cbfb691e6efdb25e1e0c4702125c13d525b52fe229f"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/enhanced-boss-bars.pw.toml"
hash = "2e079cbf315d24f1fbac7cadb09ca9f2928f99ee9ff01ed5cc58fd6b61e8439a"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "33233b588be9b7445e87c4b4ff472ffbcb9e36fe0ed2002149140b309ac5849f"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "73ddf3a0c3c88b91fcf94d0e188ced440f22d563d9aa566af206b4cd464e890a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6843022335e0f27b000ff90bf6641c5299594f5ca06331abf298b5122c6b9bcc"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
hash = "b239213b05549a5a767022bb68c058b329f4f78a58deaab139301c4c0f42ca21"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "64f7ff38d1d2b074d18eb83b1d9b5b08bb389472202ccd86ed60eb9a56b23c5a"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
hash = "04098eb2029459b6d7164ac5b6a888cac67ac80d754866a05e0bc52aaf32e6b3"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/fish-of-thieves.pw.toml"
hash = "2cedf30c336b4a332f75904c9a3481fb1a0f1360239ef4669768391b095be85b"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "62ef7e92478035b77e996189984e4749b2d876ed0a389977a2670a28f105bfd2"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "f1982207e782ffe93f3cc6b38a910fdd6d9a3630d0d61498d5eb8b31cbe14469"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "5851bef35e786bfcdb837dfc380c4bd22c857434b2997235a551b3a0cf72d158"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c949e6e0d6a70b8693ef48f8f205cb4fb967cc7c2ecbe029ffe7809e36ad5138"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "a7fd74d5d5680775d2d9b83d8a4924c0244169ffb0961dadfb901a362eb1a935"
metafile = true

[[files]]
file = "mods/immersive-ores.pw.toml"
hash = "e88320e8558a7cc62d8f4db410d36788a0598156216a4716336b3014abe655bf"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "d4a290a9bd2da03a76e63563669d76d9483d00adc77c0d5ba1d72fe4d5eaa69e"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "143102be700d30cf68d0988bc9f1b523545e37b7074ee786faac56a388e6f0e9"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "40026875ee9b7d25a4ece48faa2b70a338100e87a689d5a8d4ba1ee608b878f6"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "35c0251ad56fdf68faef3ea142fe0b76016937ab6fa52b65ce222ea7d1fb5b74"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "373b18020e519fa602dc3e5ecc7d9d1523a353ddec85b20fe8dbbad23d4e7db2"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "e72f73611904e14d915418f0e3c6cb483cdc600e211375c2eceb393fec5b80f1"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "9adb961d42928ca5f873586b6595d028dd35ff3226807d8ab41e574c68d501c7"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "53d1a831ecc5fb9713b7508fc5cfb9844375124c8e3c3fbc94699a9fe0e8004a"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
hash = "fc0625e90fc0aa50ec5db12976e51ddcb69fb47e829665cba6a124f4226fb79f"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "361f5915170fc468704db1c693cfac69431b82fdefc380d6d2d7a95242799bb9"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "5ef885f9912ff6aa73db254b63a3cd22520f06261bc3c38e7c92f449806a9044"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8c65958007f81cdf1a57dac999ec7ffdde17cce6154c9a2f75bbb389fd11efbf"
metafile = true

[[files]]
file = "mods/presence-footsteps-forge.pw.toml"
hash = "fc6fbe4edaef15637092d30600743dec1bc9bf6055f71a5ff026df108fa2b532"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "2b0772879a1d43e6fc0d892dca4a85d360e813d5cd3907fc2ab42f345b146362"
metafile = true

[[files]]
file = "mods/puffish-biome-dither.pw.toml"
hash = "a1a3ac2f960866271867639d202fc475f9cb92a48b338df62ffd134c8eeceda0"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "4eb683644ee4e38e00b06df946b71ad8fedaa860fcabbd91ec6ceb71c65b8d81"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "3dbc10daf7a2ebcbc7ff240931d5fada41900930183d48e3996d893a218f544d"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "2cb8dd9a3944a6430b49916a4fe1b6cf0bd7efd907054f8e679a02717149404f"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "086ae6b5cfa8a07be194343117c92c8139275a8dac28d4c3476081a0eb1d3386"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "f54290f9065d5f0b35215d24ea86ebfc7e4c7ce773ca6a305ec39436cef8279b"
metafile = true

[[files]]
file = "mods/sinytra-connector.pw.toml"
hash = "6db079b4b12f1b14243980080879cc40087c3507f3ad25adf97e5f0ce9bb163b"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "5240c62752415b5d66d4beffec4fe98c253eba8ebcbb2a5c1097fc3ad3de0b00"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "3bb4a9500b84afbceb8d426505a1727888aa53de23f839ce261fe6956491cc83"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "4e0171baa817919422b027a64d97ef8ffc63879c94671b2fc42f191cc6f3900d"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ee2d9154be68ef20293596a3f65810111fd35a802f1e8292e9ba8872de463a14"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "3fff9456c0ef97caab6584a10517f20822e138b627da4b26c8c46e6330d7e7cd"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "61cb40e4df3b5b700e4b983204c761f7ca8dfc61309a53400aa60c6945c700fb"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "31883f2697767614c5b0671e9600c4e584c8e60be8062867667ddfc9d2624e23"
metafile = true

[[files]]
file = "mods/tiered-forge.pw.toml"
hash = "b0a1dade8e0ac8893f9ca72bbf30b0467ee5d9353483087d7852256f63ac6534"
metafile = true

[[files]]
file = "mods/true-ending.pw.toml"
hash = "171f4c4e48ec408e9bcc6f60751da7a549d04f8e0df2d9375b48ee84fe3387ef"
metafile = true

[[files]]
file = "mods/unionlib.pw.toml"
hash = "884deddb5613373bf1271978b5703b5a8cf6bb2cee8c0e666cf61060bae8a3b5"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "557d160e4a3d856c6bbe36c39ee7c6cd42824363690b61d5f23bbac153c8edbc"
metafile = true

[[files]]
file = "options.txt"
hash = "0af8e998a3e27c8c515b55a3a070c68c5fbb90076f21a1ee2a2417ab0e03c784"

[[files]]
file = "resourcepacks/alt-compat.pw.toml"
hash = "ef0515d19e2b0f8c4a95bbbe73c9dc002365f51e3aed361f438cf5504f49c75d"
metafile = true

[[files]]
file = "resourcepacks/assembled-legendary-tooltips.pw.toml"
hash = "df91e098493582f9d80a8dab81fd32951f402934becb2d2d79dde8b6a7dfb5e1"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "f96b12a4b7a2e60865d524bb1ec052294d6d9aa59258c31d48816241bebe387a"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "15f5872ee75d21be2e6cbd25669e423a2a764312562e5cdfdc4e34af160dc6d3"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode-advancement-plaques-compat.pw.toml"
hash = "12def1ec6550ed5647ec1f3494c5e3f7711816a4f93a9b282a42e9bd0c61cd4c"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "7004a1a72df5489fc33f22be8d5afac7b2bfa8d57c83122ef3f167737b69d759"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "9f8e443df6075210eef82f35c5f95db92c19d7b1a1267a4593fa97c079993ed6"
metafile = true
