hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/fastquit.toml"
hash = "de22af584433dfdfb4a14b85091bfbd5c6be697a306499c2d7c75740658dbad4"

[[files]]
file = "config/nomorepopups.json"
hash = "3394279972b0116c3fab32a9477888da78621e0351a6dd5c2fae1ceb31cbc821"

[[files]]
file = "config/rrls.toml"
hash = "718738ffebafacec5ba69a06721ffa41e1d0b47d1b39a6905c3b21639a12cdf5"

[[files]]
file = "modlist.md"
hash = "3cd19c8db1ac43bb7a29a55e36fb3187189bad38bcae7d3f5b5cf7d11759f0b1"

[[files]]
file = "mods/advancement-plaques-fabric.pw.toml"
hash = "1d6da31544d1275e86cad36399eb9bad49588a78436dc86fdf4b489767698730"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "476e748871a05797e875dc1cd262902110365661a4cbe014bd34e6de9ed4a984"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "f53a77d8e152c94ab65a613dc222b13585b173a38141d74076a3e3ffc0575519"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "5d983e42d97fac5a2c56d4a2f49aea210b042941e4b6979eab7172a433fe60d4"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9ce55dc09b4b2a28b39ae47d146cfe5399dfc74666d9ae53811bdef4058b3491"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "0a8c22828219d1a6ee87f71bc5b46cd756612537dd4ab89383b787339f30d269"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "004aa46b68560131a4644928de6f312ef9c7ae73a180cfb53aa0f971a6d15172"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "5f13e2470d769f613652ff4378a31c86b5915fe67032c94c1be5aeed06610b4d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5fe7e26e9534cf3d7829e8c4937c7b700d2084b6345aed901c1c3de9a80f49fa"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "512a9aa7d85f3cf154f36ac8e287889e5730088fe19b8eb0b1e9409ca2ba5756"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "c4f294f47a114849b5510bba3da64503e7e714c6178dbe0edf5573065e5ef541"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "57ecfa2a5e81966ef7046d443b076e2b94c85b9f0ad8d6cb126106e3d5967dd3"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b50378ddd8de5877ce51ded7616ebbf3ad0a5e18af8125a473411fbabc6c37cd"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "c95f96c1422ed285de47a75dd9c163538fe89259d9525d15d2c07039f0c1f5b1"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "7112f698dda447ec4f1c6474683308487d51e93ec8dbe26c7f81d0fdd4c9fdb0"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "c70f66a60bcb2128e49bda671a04e96544a6fbeb9b8ee98b9c548814f237e2d5"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "23bdbf17e1fd8aeed7efeeea72741662734199dbef0b2adfac2ba795acf5ca40"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c76a6e9192ddb2a582e78d15b589188022a8fa3db09bf061d33d5f64baae81c8"
metafile = true

[[files]]
file = "mods/eating-animation-fabric.pw.toml"
hash = "ca66d992b56e2993288195caadd2a9ce2eb2dd0bfceeb396747da712bdb933bd"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "2c1d05da2179691fc1c27b53eaf942c32ff1528739a9be5e3a34dd2a92105696"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9e37d8953c537212de3dc59aec2e081979b39671ab537474f71d53666aff81b2"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "f13154c42b7c33d21560292453a5d30d701ae5c73d271b0af842d4c8cfe0b113"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "949b56f74870f3722aa82cbc0af1f34b715d62007587c3ff65c47bafb15a58bc"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
hash = "f698a4a614c690206631b2b14cd704313f14d3cb2513a5317afdab2ddad005ff"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0e28ba15ba1769864a4af0b2f7ffaa3c90017b49633bef2a843b14a46e9a791d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "be4e721e1d51831ecbc54600248be8b15ab73599d8d23cc48c95f3abdb092e0b"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "9a53d0956a5f25c6c5de1d34a6497c2d323486bf340935db6b364815aae596be"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "1bcebf42f650151bf068b968e2b27b05c4b278bb9a31f2c0b64c4a462d3ff787"
metafile = true

[[files]]
file = "mods/fish-of-thieves.pw.toml"
hash = "03f6094d13cf779813489d990430321534771076553adc51bff3b8aad6b3176b"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "d6588fade687ae5254313807598cd7732f1917e71dc202e387d11a077ab09d6c"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "ae2dd2b605e120ec04be2accfeb20938ceb4551bcc683b8c1a0f725578ea293e"
metafile = true

[[files]]
file = "mods/iceberg-fabric.pw.toml"
hash = "872ea7de2f9701ea3b96700c5a3eb7dcdf1f74cbdf1622bfc7d76250d0348f88"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "736c8917697c7640f3aceddc8e9ce2eac770048c3e3163aa16a7872d5bb04c45"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "db9e913bf3d616453eda6a487e624c9a8708be57af5f596a6a0e7044ff021534"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "40fa748597b1da468d9d0ef756ab55bb591e214695b93ef66feafd7cd6520a33"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b31e45972ba08291e168f9d93ed14d679a8799983b7bce7ca38faa795a85bf3a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "f7c9c1bee75968286a4fb6a765f7cd0505fac90cac30a896f76215c1e6d4d8bd"
metafile = true

[[files]]
file = "mods/legendary-tooltips-fabric.pw.toml"
hash = "1c82d097cf9bb25109c5439e3676d7a26090d8679a1db98daa8dd1d52d32a88b"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "0111e250e04a831514a49464405579fb36b4b8b61dc15928e15a2a805dc569a0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "94944bc843327b8c13b34ee3ea4c16671d3102d5ae6845a48e5c86592d9696bb"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "a3e8ab5b65ff403b1e578f50465a67743ff2d6943bd47458be482e44f5642754"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "756e9021d46a85cc4a8f89e9f71c0ac6031e8e40b41004fd2915bf2cbe64cd99"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c2fe9a1900ceb3a6014ccb83344aa4ab5ddf65c8bf660044469c3c90c7ed9010"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0a294ec59f287931a4748716730aa3a5509a778bb5c39eab881f21bdfef273e5"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3cd8155341a4233955ff9892a3b7b5da6dc6d8d892863b2f544328f2731f7f03"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0c3e67242799f8dca62ba5bba5556d72d13d6247c4092eab28a0a0be5b93fdff"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "53633508694b314c003866564cc4b8099982ec840d18d21b761459513a253f8c"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
hash = "82c5501ec0543e249a0b3efcd3b66e517c9842aeeebd807a9c40fb7738d5a647"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "8aecc1933ce47b6b68c7fe5bde311324fcff1f81fad51e27811e78f39ce0df15"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "75d42d0a0bcfbcce376fb229f72b75e3a40592fdff5490b997c19ef439a9c832"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4450b4162b40ff483495103ed9646d5b65e8652876495b084473cfc7e29ece5a"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "326a6de0170cc13b983119690ec173cb2bc6aed1e4a4ac5070bf98893d1587da"
metafile = true

[[files]]
file = "mods/prism-fabric.pw.toml"
hash = "d42c9ad05fd54d790fd76ea0f10665fffcd6413a6da0d1810879398ac66d6133"
metafile = true

[[files]]
file = "mods/puffish-biome-dither.pw.toml"
hash = "dcd6f7447fee9226c8e2e9d5d0dedfcc2eae04004a1559a9e829c1012ada1f13"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2494505990ebe04a740fbae936efdf4d24a52071c04d3b73d215b9539e59817b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6dff4b6eccb5ecca2c5b15bf8e24523298819839db487f02a65636c2fbe3fdd1"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "44a680557c1ab773a1121984e6ddb67c56eb043a1716a2ca1cdfa6cd3e855372"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "795a73207734f08e5cece4da342c509d2210787ea8f0df9ea7ee440719a53cf3"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "9a1fe392eaf20ffe44d8c106b5767588703e391cfbdde639f7790952db0538c6"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "4fd9feb68cb218528c315e854abfe33934a34ab2a067e8f24b002075ceb1342b"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e4b0fcff8630f9c3919d1ffa6e519c4fb9e8d814d6c321ad2374877863e84b51"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "bd4cfd8701633c013cacde0c311a24261020abdce657e3760166d6af8660f745"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "69d9366753ade6e5dbcbbac31372fae83d6b37b81a63a797a217aa69e97f2992"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "898e14275dd5cc187dee2b8f8fc83b4f0cdb56430b7fa64a8055e006d0249ce7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "dc64fa7d848e9dbb47917b2512896e28f4b23a0d9a3585aab37fcc5393a272ee"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "503a13fb7a8188f8434a82df32c16644cba3d0f25e31da88626acc52af03da41"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "87f0c2e2375209d074e05608e47f71bebece1955065b2b523576353cbb5f0b67"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "4541ffb5d428821404813cbb6447a18900d7c051dcd66c9ede384224f6ee99e5"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "605e24df28c2facc0e22397656ff507548b86badc0a8fbc278c72f6ccd3da242"
metafile = true

[[files]]
file = "mods/true-ending.pw.toml"
hash = "c98091a3c98f5bf8f512541d6e003e3d87bb0bdec6f0d07c7f5948607b2680e9"
metafile = true

[[files]]
file = "mods/tschipcrafts-dynamic-lights-mod.pw.toml"
hash = "aaa2f62b1cf52930cfacf34b991b16b5526100584c2cecf55f823823ad1541ef"
metafile = true

[[files]]
file = "mods/vanilla-backpacks.pw.toml"
hash = "5f436b48c6139aebb13a43c3476b4d32a415ecb5ac82d2074f343374fa2880f4"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "edc4eddf876b4429bf33ca8febbd4c8cec6a08de2ac4cfcffcf8d95861773b16"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f8b22a3818eb55e9b7eafa4cc6b1b44482b88524d4134d544dfb795d9aea058d"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "1836c4b896229b4283d28009951c913b518df7aefd0ccb05f12cd954c3a7deb8"
metafile = true

[[files]]
file = "options.txt"
hash = "55bb3fb4fd9bc197d13a6960d0d09a1b52ad2d3c1ba1737fa77f37d59bcbe7b7"

[[files]]
file = "resourcepacks/alt-compat.pw.toml"
hash = "ef0515d19e2b0f8c4a95bbbe73c9dc002365f51e3aed361f438cf5504f49c75d"
metafile = true

[[files]]
file = "resourcepacks/assembled-legendary-tooltips.pw.toml"
hash = "da64c7ec3e8b0b902cff6d70eefb583a406fd18742e8b190f9a66b98efb5d996"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "dc065d9bb3aaad0eefdf5158211929943835493c709e2fb7ed29a6d246ea9c06"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "3742efd536b417560395d9aab9643e2a97c105a60fd7f37c9a825024c7479359"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "15f5872ee75d21be2e6cbd25669e423a2a764312562e5cdfdc4e34af160dc6d3"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode-advancement-plaques-compat.pw.toml"
hash = "12def1ec6550ed5647ec1f3494c5e3f7711816a4f93a9b282a42e9bd0c61cd4c"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "7004a1a72df5489fc33f22be8d5afac7b2bfa8d57c83122ef3f167737b69d759"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "9f8e443df6075210eef82f35c5f95db92c19d7b1a1267a4593fa97c079993ed6"
metafile = true
