hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/fastquit.toml"
hash = "de22af584433dfdfb4a14b85091bfbd5c6be697a306499c2d7c75740658dbad4"

[[files]]
file = "config/no-more-popups.json"
hash = "b117398527e106b0eec62d3764ebcc94d47e15b2695cc2f8f93d9ddb6ae77cc5"

[[files]]
file = "config/rrls.toml"
hash = "718738ffebafacec5ba69a06721ffa41e1d0b47d1b39a6905c3b21639a12cdf5"

[[files]]
file = "modlist.md"
hash = "bd8e44ff6cb17a4cb60f9f2b322932a791d72147b6a04dc14d6dd06ca10237d8"

[[files]]
file = "mods/advancement-plaques-fabric.pw.toml"
hash = "1d6da31544d1275e86cad36399eb9bad49588a78436dc86fdf4b489767698730"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "2c187ad51a314cdc033c2dd068815d1b3b6a8995017b570c58bba279066aaa2b"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "901cae0aef0fa9ae21afd431f9a0a483108bee39e07c3f852c065251a0f07af4"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "9d0359979f578be47aaf8b37b1086c7b8dd490b9811ecdaf7de03f99ac80402c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9ce55dc09b4b2a28b39ae47d146cfe5399dfc74666d9ae53811bdef4058b3491"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "0a8c22828219d1a6ee87f71bc5b46cd756612537dd4ab89383b787339f30d269"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e2f2a6f6ff38054ce8d91a43a20b79ea7b4e84cb924142fb7d2bcfdd95fe5b57"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "5f13e2470d769f613652ff4378a31c86b5915fe67032c94c1be5aeed06610b4d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "5fe7e26e9534cf3d7829e8c4937c7b700d2084b6345aed901c1c3de9a80f49fa"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "512a9aa7d85f3cf154f36ac8e287889e5730088fe19b8eb0b1e9409ca2ba5756"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "d2477bde2046b9d2021acbd206915d63eceba39309f20f697aaa06533278bef0"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "ddc63d9d556dd806201519fc989f33aaf12563864d47c60bee590b92395fa4a5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b50378ddd8de5877ce51ded7616ebbf3ad0a5e18af8125a473411fbabc6c37cd"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "c95f96c1422ed285de47a75dd9c163538fe89259d9525d15d2c07039f0c1f5b1"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "8218d022a24d23423f7fa01b8705fd5c4c3be8084a19102433843bd203f38f1d"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "c92fd4a87e1ddbe0b9288a38cbf1491e4ba933eaeb4c209f7861de0235b2c81a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "23bdbf17e1fd8aeed7efeeea72741662734199dbef0b2adfac2ba795acf5ca40"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "79a29ea91ba2e93faa2f7886e9c94a69db4d42bff295371515d8eaf2c4728af0"
metafile = true

[[files]]
file = "mods/eating-animation-fabric.pw.toml"
hash = "ca66d992b56e2993288195caadd2a9ce2eb2dd0bfceeb396747da712bdb933bd"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "2c1d05da2179691fc1c27b53eaf942c32ff1528739a9be5e3a34dd2a92105696"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b8e7e67084c9398b85143e0ecaf302e52d13e4ad036634a4fb800027123a8c75"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "fa7fc7c2c05fee8678ffdef46da1847018183e3cfb6152bdec4619765c37e852"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "068520363709db9632207ee223dcdc9dc3a33b295806b07b0f4e6b0556b9009a"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
hash = "f698a4a614c690206631b2b14cd704313f14d3cb2513a5317afdab2ddad005ff"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0364a64e7f6515dccf92e10512c81178b7afeb1ae031f8024620892769e69313"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c27a08b54ab9b474a57211f383f511d67fd0023035ee2e76d247667e15183e63"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "be4e721e1d51831ecbc54600248be8b15ab73599d8d23cc48c95f3abdb092e0b"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "9a53d0956a5f25c6c5de1d34a6497c2d323486bf340935db6b364815aae596be"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3aa66d677f5f23ddc8528f0c3243a9cbded0e27ea4b3db089ec0c8deecfb5704"
metafile = true

[[files]]
file = "mods/fish-of-thieves.pw.toml"
hash = "dccab90a3b30131fcbfd0e03d04863c49215a359a325b1a3a0777d6cfc1c146c"
metafile = true

[[files]]
file = "mods/free-inventory.pw.toml"
hash = "a1396d8ed31795e01d54e16b25aa4b61ffbc2d4790b087faaaf2c1282dc1be6a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "7e772dbc24a23ed3eafa8d6c1e7a8fb21d0085ee06028216362daea8206938c4"
metafile = true

[[files]]
file = "mods/iceberg-fabric.pw.toml"
hash = "872ea7de2f9701ea3b96700c5a3eb7dcdf1f74cbdf1622bfc7d76250d0348f88"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "1c5e90c7879f5bbf069055aa60d04a86d8c80417b0a47d72b47cf16e3fb05f32"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "db9e913bf3d616453eda6a487e624c9a8708be57af5f596a6a0e7044ff021534"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "ac595381310fefa95b5592b376bc46978bee6dcf839f4a8ff67d168bbbabb887"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b31e45972ba08291e168f9d93ed14d679a8799983b7bce7ca38faa795a85bf3a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "f7c9c1bee75968286a4fb6a765f7cd0505fac90cac30a896f76215c1e6d4d8bd"
metafile = true

[[files]]
file = "mods/legendary-tooltips-fabric.pw.toml"
hash = "1c82d097cf9bb25109c5439e3676d7a26090d8679a1db98daa8dd1d52d32a88b"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "0111e250e04a831514a49464405579fb36b4b8b61dc15928e15a2a805dc569a0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "4af07dd765be426fec46e72aa0a0b435b42d85bffe1ee87a100e661d881c90f2"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "2edafdc423051b21edbe49f433e73e6ba3164dfb079673355003e0f889e7ddf3"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "756e9021d46a85cc4a8f89e9f71c0ac6031e8e40b41004fd2915bf2cbe64cd99"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c2fe9a1900ceb3a6014ccb83344aa4ab5ddf65c8bf660044469c3c90c7ed9010"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0a294ec59f287931a4748716730aa3a5509a778bb5c39eab881f21bdfef273e5"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3cd8155341a4233955ff9892a3b7b5da6dc6d8d892863b2f544328f2731f7f03"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0c3e67242799f8dca62ba5bba5556d72d13d6247c4092eab28a0a0be5b93fdff"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "7a5d6a474afc81f35c56431a5a123ac567b85b2e01dbd928bee55816b94bb55f"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
hash = "82c5501ec0543e249a0b3efcd3b66e517c9842aeeebd807a9c40fb7738d5a647"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "b56b99f382b254d020cc5772f3636a565cc6503550ddac00e3d9cafad582cb63"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "75d42d0a0bcfbcce376fb229f72b75e3a40592fdff5490b997c19ef439a9c832"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4450b4162b40ff483495103ed9646d5b65e8652876495b084473cfc7e29ece5a"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "326a6de0170cc13b983119690ec173cb2bc6aed1e4a4ac5070bf98893d1587da"
metafile = true

[[files]]
file = "mods/prism-fabric.pw.toml"
hash = "d42c9ad05fd54d790fd76ea0f10665fffcd6413a6da0d1810879398ac66d6133"
metafile = true

[[files]]
file = "mods/puffish-biome-dither.pw.toml"
hash = "dcd6f7447fee9226c8e2e9d5d0dedfcc2eae04004a1559a9e829c1012ada1f13"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2494505990ebe04a740fbae936efdf4d24a52071c04d3b73d215b9539e59817b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6dff4b6eccb5ecca2c5b15bf8e24523298819839db487f02a65636c2fbe3fdd1"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "44a680557c1ab773a1121984e6ddb67c56eb043a1716a2ca1cdfa6cd3e855372"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "795a73207734f08e5cece4da342c509d2210787ea8f0df9ea7ee440719a53cf3"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "c6639db718ea971ef2506fffa11780b2ae30b0e2256f68cd2ba969b5ad15fb8e"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "4fd9feb68cb218528c315e854abfe33934a34ab2a067e8f24b002075ceb1342b"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "090c32358b667855c299bad2592d85678a723f09cdeb36c76edd84ee08811744"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "bd4cfd8701633c013cacde0c311a24261020abdce657e3760166d6af8660f745"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "69d9366753ade6e5dbcbbac31372fae83d6b37b81a63a797a217aa69e97f2992"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "898e14275dd5cc187dee2b8f8fc83b4f0cdb56430b7fa64a8055e006d0249ce7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "dc64fa7d848e9dbb47917b2512896e28f4b23a0d9a3585aab37fcc5393a272ee"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "503a13fb7a8188f8434a82df32c16644cba3d0f25e31da88626acc52af03da41"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "87f0c2e2375209d074e05608e47f71bebece1955065b2b523576353cbb5f0b67"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "0ee2813f3ef4e2d1226b9bf4caf71b846dfc0ac6cd58276d1c1416e33607d29c"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "605e24df28c2facc0e22397656ff507548b86badc0a8fbc278c72f6ccd3da242"
metafile = true

[[files]]
file = "mods/true-ending.pw.toml"
hash = "c98091a3c98f5bf8f512541d6e003e3d87bb0bdec6f0d07c7f5948607b2680e9"
metafile = true

[[files]]
file = "mods/tschipcrafts-dynamic-lights-mod.pw.toml"
hash = "aaa2f62b1cf52930cfacf34b991b16b5526100584c2cecf55f823823ad1541ef"
metafile = true

[[files]]
file = "mods/vanilla-backpacks.pw.toml"
hash = "5f436b48c6139aebb13a43c3476b4d32a415ecb5ac82d2074f343374fa2880f4"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "edc4eddf876b4429bf33ca8febbd4c8cec6a08de2ac4cfcffcf8d95861773b16"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "5b3d17e43a7ca6e877bad85b838a8c38f42d8c3922e305b7d88c723a0e573a48"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "813dc67a4b0f6040008993731ce8709b7eec76040560b28e47610d92cf97bfdd"
metafile = true

[[files]]
file = "options.txt"
hash = "d286fd055bced60b052dc0433d33854c0c46317870c1f95bd726631e0c2d3211"

[[files]]
file = "resourcepacks/connected-bricks.pw.toml"
hash = "b1f6d18e011da27a5441fb7d1749e6df70f7965aa23a318f1143f8cc1745ad0f"
metafile = true

[[files]]
file = "resourcepacks/connected-paths.pw.toml"
hash = "cf3afec835a28f29a0f29468c6604b40d3fe4e2578a1b84876871c63f7a93b42"
metafile = true

[[files]]
file = "resourcepacks/connected-rocks.pw.toml"
hash = "86c9ec0b0d0d1cc3226f40116e25bb573e987d905bde72c81644e19ef9d4dc51"
metafile = true

[[files]]
file = "resourcepacks/crystal-tooltips.pw.toml"
hash = "1915e613b09d0ef21ef55dc82a3c9f84f1be0a5004b78ecf4754c81423f0587f"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "3742efd536b417560395d9aab9643e2a97c105a60fd7f37c9a825024c7479359"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "72b919a0242253a1540a0fa424ea5a652787365186ac9f5fa5a67583bb5d368c"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode-advancement-plaques-compat.pw.toml"
hash = "12def1ec6550ed5647ec1f3494c5e3f7711816a4f93a9b282a42e9bd0c61cd4c"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "c3c618df6fa8e9f4b8de628c050cde77fec5fac7778a38ac94b28f42183e3a2a"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "753adc976b00bdb2f4e060e18700d778d0938c76805c46747acccb139fdc7025"
metafile = true
