name = "Toralia"
author = "Alfakynz"
version = "1.0.0-a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4983d4b4588165bbc4d0b3ccbadf634a0b835e0004e88fffa8ee93114445225a"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
