name = "Toralia"
author = "Alfakynz"
version = "1.0.0-a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19b05f895d2780b1ebb72e5234e6449f67a30c60bb13dfdb5205a580c9db5c11"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
