name = "Toralia"
author = "Alfakynz"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a056d68610e242239d7a8edcafbc61f3e01baeb3e6ddde1e54d1e1f1ded647eb"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
